package Team_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Connect();
    }
    Connection con;
    PreparedStatement pst;

    int cnt = 0;

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/team", "root", "");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textf3 = new javax.swing.JTextField();
        combobox4 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 51));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Team Selection for Competitive Programming");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 0));
        jButton1.setText("Submit");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 102));
        jButton2.setText("Show Team");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Student_specialty");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Total_students");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Student_name");

        combobox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Math", "Algorithm", "Code", " " }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Specialty_type");

        r1.setBackground(new java.awt.Color(51, 0, 51));
        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(255, 255, 51));
        r1.setText("Very Good");
        r1.setActionCommand("Good");

        r3.setBackground(new java.awt.Color(51, 0, 51));
        buttonGroup1.add(r3);
        r3.setForeground(new java.awt.Color(255, 255, 51));
        r3.setText("Average");
        r3.setActionCommand("Good");

        r2.setBackground(new java.awt.Color(51, 0, 51));
        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(255, 255, 51));
        r2.setText(" Good");
        r2.setActionCommand("Good");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textf3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(textf1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(r2)
                                            .addComponent(r1)
                                            .addComponent(r3)
                                            .addComponent(jButton2))))))))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(r2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        if (textf1.getText().equals("") && textf3.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Must be fillup");
        }
        String no = textf1.getText();
        int n = Integer.parseInt(no);

        String name = textf3.getText();
        String Speciality = combobox4.getSelectedItem().toString();

        try {

            if (Speciality == "Math" && r3.isSelected() == true) {
                cnt++;

                if (cnt > n) {
                    JOptionPane.showMessageDialog(this, "Don't matching input number of students");

                    //textf2.setText("");
                    textf3.setText("");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                } else if (cnt > 0) {
                    pst = con.prepareStatement("insert into Math (name,Speciality)values(?,?)");

                    pst.setString(1, name);
                    pst.setString(2, Speciality);
                    int k = pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Inserted successfully");

                    //textf2.setText("");
                    textf3.setText("");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(this, "Error");
                }

            } else if (Speciality == "Algorithm" && r2.isSelected() == true) {
                cnt++;
                

                if (cnt > n) {
                    JOptionPane.showMessageDialog(this, "Don't matching input number of students");

                    //textf2.setText("");
                    textf3.setText("");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                } else if (cnt>0) {
                    
                    pst = con.prepareStatement("insert into Algorithm (name,Speciality)values(?,?)");

                pst.setString(1, name);
                pst.setString(2, Speciality);
                int k = pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Inserted successfully");

                    //textf2.setText("");
                    textf3.setText(" ");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(this, "Error");
                    textf3.setText(" ");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();
                }

            } else if (Speciality == "Code" && r1.isSelected() == true) {
                cnt++;
                
                if (cnt > n) {
                    JOptionPane.showMessageDialog(this, "Don't matching input number of students");

                    //textf2.setText("");
                    textf3.setText("");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                } else if (cnt>0) {
                    pst = con.prepareStatement("insert into Code (name,Speciality)values(?,?)");

                pst.setString(1, name);
                pst.setString(2, Speciality);
                int k = pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Inserted successfully");

                    //textf2.setText("");
                    textf3.setText("");
                    combobox4.setSelectedIndex(-1);
                    textf3.requestFocus();

                } else {
                    JOptionPane.showMessageDialog(this, "Error");
                }

            } else {
               
                if(Speciality != "Math" && r3.isSelected() != true)
                {
                    cnt++;
                     JOptionPane.showMessageDialog(this, "inserted successfully");
                   
                }
                else if(Speciality != "Algorithm" && r2.isSelected() != true)
                {
                    cnt++;
                    JOptionPane.showMessageDialog(this, "inserted successfully");
                    
                }
                else{
                    cnt++;
                     JOptionPane.showMessageDialog(this, "inserted successfully");
                   
                }
                
                if(cnt>n)
                {
                    JOptionPane.showMessageDialog(this, "Don't matching input number of students");

                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    
                }
             

            }

        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/team", "root", "")) {
            String sqlQuery = "INSERT INTO combined_table (stud1_name, stud1_speciality, stud2_name, stud2_speciality, stud3_name, stud3_speciality)\n"
                    + "SELECT DISTINCT math.name AS stud1_name, math.Speciality AS stud1_speciality,\n"
                    + "                code.name AS stud2_name, code.Speciality AS stud2_speciality,\n"
                    + "                algorithm.name AS stud3_name, algorithm.speciality AS stud3_speciality\n"
                    + "FROM math\n"
                    + "INNER JOIN code ON math.id = code.id\n"
                    + "INNER JOIN algorithm ON math.id = algorithm.id\n"
                    + "WHERE NOT EXISTS (\n"
                    + "    SELECT 1\n"
                    + "    FROM combined_table\n"
                    + "    WHERE combined_table.stud1_name = math.name\n"
                    + "    AND combined_table.stud1_speciality = math.Speciality\n"
                    + "    AND combined_table.stud2_name = code.name\n"
                    + "    AND combined_table.stud2_speciality = code.Speciality\n"
                    + "    AND combined_table.stud3_name = algorithm.name\n"
                    + "    AND combined_table.stud3_speciality = algorithm.speciality\n"
                    + ")";

            try (PreparedStatement pst = con.prepareStatement(sqlQuery)) {
                pst.execute(); // Executes the prepared statement
                //System.out.println("Data inserted successfully.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        //System.out.println(cnt);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        Show_team s = null;
        try {
            s = new Show_team();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        s.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combobox4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JTextField textf1;
    private javax.swing.JTextField textf3;
    // End of variables declaration//GEN-END:variables

}
